<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.12" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Win32.Interoperability" Version="11.3.12" />
    <PackageReference Include="DeftSharp.Windows.Input" Version="0.10.0" />
    <PackageReference Include="LibVLCSharp" Version="3.9.6" />
    <PackageReference Include="LibVLCSharp.Avalonia" Version="3.9.6" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NodaTime" Version="3.3.1" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="OpenAI" Version="2.9.1" />
    <PackageReference Include="ReactiveUI" Version="23.1.8" />
    <PackageReference Include="Splat" Version="19.3.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.Formats.Asn1" Version="10.0.5" />
    <PackageReference Include="System.Management" Version="10.0.5" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="UI\Dialogs\AvErrorDialog.axaml.cs">
      <DependentUpon>AvErrorDialog.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>