<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.3" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.0.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.0.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.16" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
    <PackageReference Include="Avalonia.Win32.Interoperability" Version="12.0.3" />
    <PackageReference Include="AvaloniaEdit.TextMate" Version="12.0.0" />
    <PackageReference Include="DeftSharp.Windows.Input" Version="0.10.0" />
    <PackageReference Include="FluentFTP" Version="54.1.2" />
    <PackageReference Include="LibVLCSharp" Version="3.9.7.1" />
    <PackageReference Include="LibVLCSharp.Avalonia" Version="3.9.7.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0-preview1.26124.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.7.1207" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="NodaTime" Version="3.3.2" />
    <PackageReference Include="Nostr.Client" Version="2.1.0" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="OpenAI" Version="2.10.0" />
    <PackageReference Include="ReactiveUI" Version="23.2.27" />
    <PackageReference Include="Splat" Version="19.3.1" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.Formats.Asn1" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="System.Management" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="TextMateSharp" Version="2.0.3" />
    <PackageReference Include="TextMateSharp.Grammars" Version="2.0.3" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="UI\Dialogs\AvErrorDialog.axaml.cs">
      <DependentUpon>AvErrorDialog.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>