/* ================================================================================================= *
 * 2025.11.10 - JLW
 *      This is the JAXBase SQL class.  It's a front-end that uses SQLClass objects
 *      for MSSQL, MySQL, and PostgreSQL
 * 
 *      Engine property will determine what type of backend.
 * 
 *      Value   Description
 *          0   Not initialized
 *          1   MS SQL Server
 *          2   MySQL
 *          3   PostgreSQL
 *          
 *          
 * 2025.11.15 - JLW
 *      Now that I'm into it and have the code written for MS SQL, MySQL, and PostgreSQL, 
 *      I realize I could have made a class and subclassed the different engines.  
 *      Not a biggie and, once again, something to remember for Version 2.
 * 
 *      I am stopping with the three engines for Version 1 and will make plans for more 
 *      engines in Version 2.  I have had some thoughts about adding in NOSQL capabilities 
 *      to support Mongo, NOSQL, and Apache Cassandra.  However, I don't think that's
 *      worth the effort for Version 2 unless some really talented people were to
 *      sign on to help.
 *      
 * 2025.11.16 - JLW
 *      I got my Merlin SQL Server back up and will start testing soon.
 *      
 * 2025.12.14 - JLW
 *      Got around to testing and basics look good. Moving on to other things.
 *      
 * 2026.04.02 - JLW
 *      Avalonia requires ASYNC everywhere and since I'm now deciding to make
 *      JAXBase thread safe and capable, I decided that the SQL object is 
 *      also going to be thread safe and ASYNC capable so planning now begins
 *      on how to make it work as an ASYNC capable class.
 *      
 *      This could be an major selling point for JAXBase.
 * 
 * 2026.05.27 - JLW
 *      Back to clean up and get SQL Server and MySQL engines fleshed out and
 *      ready for integration into the language.  The goal is to have as many
 *      DBF commands capable of working with the SQL system as possible.
 *      
 *      Since SQL tables are not built like a DBF table, all SQL tables are 
 *      expected to have an integer or string primary key in order to work
 *      correctly in the JAXBase language.  JAXBase will provide tools to
 *      help autocreate primary keys that need to be generated by the code.
 * 
 * ================================================================================================= */
using JAXBase.Core;
using JAXBase.Data;
using JAXBase.Utilities;
using System.Text.RegularExpressions;

namespace JAXBase.XBase
{
    public class XBase_Class_SQL : XBase_Class_Avalonia
    {
        public new string MyBaseClass = "SQL";
        public new string MyDefaultName = "sql";
        public SQLClass MyConnection => (SQLClass)me.nvObject!;

        private string propCursorName;
        private string propCursorResult;
        private string propEngine;
        private string propConnectString;
        private string methConnect;

        public XBase_Class_SQL(JAXObjectWrapper jow, string name) : base(jow, name)
        {
            name = string.IsNullOrEmpty(name) ? "sql" : name;
            SetVisualObject(null, "SQL", name, false, UserObject.urw);
            me.nvObject = new XBase_ClassSQL_NONE(this);

            propCursorName = Program.CurrentApp.ActiveLanguagePack.RevPEMs.TryGetValue("cursorname", out string? p) ? p : "cursorname";
            propCursorResult = Program.CurrentApp.ActiveLanguagePack.RevPEMs.TryGetValue("cursorresult", out p) ? p : "cursorresult";
            propEngine = Program.CurrentApp.ActiveLanguagePack.RevPEMs.TryGetValue("engine", out p) ? p : "engine";
            propConnectString = Program.CurrentApp.ActiveLanguagePack.RevPEMs.TryGetValue("connectionstring", out p) ? p : "connectionstring";
            methConnect= Program.CurrentApp.ActiveLanguagePack.RevPEMs.TryGetValue("connect", out p) ? p : "connect";
        }

        public string CurrentCursorName = "";


        public override async Task<bool> PostInit(JAXObjectWrapper? callBack, List<ParameterClass> parameterList)
        {
            // ----------------------------------------
            // Final setup of properties
            // ----------------------------------------
            bool result = await base.PostInit(callBack, parameterList);

            return result;
        }


        /*------------------------------------------------------------------------------------------*
         * 
         * Non visual classes will typically call here to get the value of the 
         * property from the UserProperties dictionary.
         * 
         * Return INT result
         *      0   - Successfully proccessed
         *      1   - Just saved to UserProperties
         *      2   - Requires special handling, did not process
         *      >10 - Error code
         *      
         *------------------------------------------------------------------------------------------*/
        public override async Task<JAXObjects.Token> GetProperty(string propertyName, int idx)
        {
            JAXObjects.Token returnToken = new();
            int result = 0;

            propertyName = propertyName.ToLower();
            string EnglishPropertyName = Program.CurrentApp.ActiveLanguagePack.PEMs.TryGetValue(propertyName, out string? p) ? p : propertyName;

            if (UserProperties.ContainsKey(propertyName))
            {
                switch (EnglishPropertyName.ToLower())
                {
                    case "connectionstring":
                        if (MyConnection is not null)
                            returnToken.Element.Value = MyConnection.GetConnectionString();
                        else
                            returnToken.Element.Value = string.Empty;
                        break;
                    case "isconnected":
                        if (MyConnection is not null && MyConnection.GetState() == 1)
                            returnToken.Element.Value = true;
                        else
                            returnToken.Element.Value = false;
                        break;

                    case "state":
                        if (MyConnection is not null)
                            returnToken.Element.Value = MyConnection.GetState();
                        else
                            returnToken.Element.Value = 0;
                        break;

                    // Intercept special handling of properties
                    default:
                        // Process standard properties
                        returnToken = await base.GetProperty(propertyName, idx);
                        result = returnToken.Element.IsNull() ? 1 : 0;
                        break;
                }

                if (JAXLib.Between(result, 1, 10))
                {
                    result = 0;
                    returnToken.CopyFrom(UserProperties[propertyName]); //returnToken.Element.Value = UserProperties[propertyName].Element.Value;
                }
            }
            else
                result = 1559;

            if (result > 10)
            {
                _AddError(result, 0, string.Empty, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                if (string.IsNullOrWhiteSpace(Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure))
                    AppErrorHandling.SetError(result, $"{result}|", string.Empty);

                returnToken.Element.MakeNull();
            }
            else
                result = 0;

            return returnToken;
        }


        /*------------------------------------------------------------------------------------------*
         * Handle the commmon properties by calling the base and then
         * handle the special cases.
         * 
         * Return result from XBase_Visual_Class
         *      0   - Successfully proccessed
         *      1   - Did not process
         *      2   - Requires special processing
         *      >10 - Error code
         * 
         * 
         * Return from here
         *      0   - Successfully processed
         *     -1   - Error Code
         *      
         *------------------------------------------------------------------------------------------*/
        public override async Task<int> SetProperty(string propertyName, object objValue, int objIdx)
        {
            int result = 0;

            propertyName = propertyName.ToLower();
            string EnglishPropertyName = Program.CurrentApp.ActiveLanguagePack.PEMs.TryGetValue(propertyName, out string? p) ? p : propertyName;

            JAXObjects.Token tk = new();
            tk.Element.Value = objValue;

            if (UserProperties.ContainsKey(propertyName) && UserProperties[propertyName].Protected)
                result = 3026;
            else
            {
                if (UserProperties.ContainsKey(propertyName))
                {
                    switch (EnglishPropertyName)
                    {
                        // Intercept special handling of properties
                        case "appname":
                        case "schema":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("C") == false)
                                    result = 11;
                                else if (AppHelper.IsLegalObjectName(tk.AsString()) == false && tk.AsString().Length < 65)
                                    result = 41;

                            }
                            else
                                result = 3100;
                            break;

                        case "cursorname":
                            // Special case, is a string only unless starts with a paren then evaluated
                            string cname = tk.AsString().Trim();

                            if (cname.Length == 0)
                                cname = me.cPropSQLResult;

                            objValue = cname;
                            break;

                        case "database":
                        case "driver":
                        case "name":
                        case "password":
                        case "server":
                        case "userid":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("C") == false)
                                    result = 11;
                            }
                            else
                                result = 3100;
                            break;

                        case "comment":
                        case "tag":
                            if (tk.Element.Type.Equals("C") == false)
                                result = 11;
                            break;

                        case "connectionstring":
                            if (tk.Element.Type.Equals("C") == false)
                                result = 11;
                            else
                                result = await MyConnection.SetParameterString(tk.AsString());
                            break;

                        case "authtype":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("N") == false)
                                    result = 11;
                                else if (JAXLib.Between(tk.AsInt(), 0, 2) == false)
                                    result = 41;
                            }
                            else
                                result = 3100;
                            break;


                        case "engine":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("N") == false)
                                    result = 11;
                                else if (JAXLib.Between(tk.AsInt(), 0, 3) == false)
                                    result = 41;
                            }
                            else
                                result = 3100;
                            break;


                        case "port":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("N") == false)
                                    result = 11;
                                else if (JAXLib.Between(tk.AsInt(), 0, 65535) == false)
                                    result = 41;
                            }
                            else
                                result = 3100;
                            break;

                        case "packetsize":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("N") == false)
                                    result = 11;
                                else if (JAXLib.Between(tk.AsInt(), 512, 32767) == false)
                                    result = 41;
                            }
                            else
                                result = 3100;
                            break;

                        case "connecttimeout":
                        case "idletimeout":
                        case "querytimeout":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("N") == false)
                                    result = 11;
                                else if (JAXLib.Between(tk.AsInt(), 0, 86400) == false)
                                    result = 41;
                            }
                            else
                                result = 3100;
                            break;

                        case "asynchronous":
                        case "batchmode":
                        case "dispwarnings":
                        case "encryption":
                        case "shared":
                        case "trust":
                            if (MyConnection is null || MyConnection.GetState() == 0)
                            {
                                if (tk.Element.Type.Equals("L"))
                                {
                                    // It's a logical so do nothing
                                }
                                else if (tk.Element.Type.Equals("N"))
                                    objValue = tk.AsInt() == 0 ? 0 : 1;
                                else
                                    result = 11;
                            }
                            else
                                result = 3100;
                            break;

                        default:
                            result = 1;
                            break;
                    }

                    // Do we need to process this property?
                    if (JAXLib.Between(result, 0, 10))
                    {
                        if (result < 9)
                            UserProperties[propertyName].Element.Value = objValue;

                        result = 0;
                    }
                }
                else
                    result = 1559;

                // Deal with errors
                if (result > 10)
                {
                    _AddError(result, 0, string.Empty, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);

                    if (string.IsNullOrWhiteSpace(Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure))
                        AppErrorHandling.SetError(result, $"{result}|", string.Empty);

                    result = -1;
                }
                else
                    result = 0;
            }

            return result;
        }

        /*
         * This is where the default actions for the methods occur
         */
        public override async Task<int> DoDefault(string methodName)
        {
            int result = 0;
            string errMsg = string.Empty;

            methodName = methodName.ToLower();
            string EnglishMethodName = Program.CurrentApp.ActiveLanguagePack.PEMs.TryGetValue(methodName, out string? p) ? p : methodName;

            // Set up the cursorresult property
            string cname = UserProperties[propCursorName].AsString();
            UserProperties[propCursorResult].Element.Value = "";

            // Solve for cname?
            if (cname[0].Equals('('))
            {
                // Do the math after stripping the parens
                cname = cname[1..].Trim();
                cname = cname[..^1].Trim();

                GenericClass gc = await Program.CurrentApp.JaxMath.SolveMath(cname);
                cname = gc.Value.AsString();

                if (string.IsNullOrWhiteSpace(cname))
                    result = 41;
                else
                {
                    if (Program.CurrentApp.CurrentDS.IsWorkArea(cname))
                        await Program.CurrentApp.CurrentDS.CloseDBF(cname);
                }
            }


            AppIO.DebugLog($"Calling SQL.{methodName} with cursor result as {cname}");

            int parms = Program.CurrentApp.ParameterClassList.Count;

            JAXObjects.Token parm1 = new("");
            if (parms > 0)
                parm1.CopyFrom(Program.CurrentApp.ParameterClassList[0].token);

            JAXObjects.Token parm2 = new("");
            if (parms > 1)
                parm2.CopyFrom(Program.CurrentApp.ParameterClassList[1].token);

            JAXObjects.Token parm3 = new("");
            if (parms > 2)
                parm3.CopyFrom(Program.CurrentApp.ParameterClassList[2].token);

            JAXObjects.Token parm4 = new("");
            if (parms > 3)
                parm4.CopyFrom(Program.CurrentApp.ParameterClassList[3].token);

            JAXObjects.Token parm5 = new("");
            if (parms > 4)
                parm5.CopyFrom(Program.CurrentApp.ParameterClassList[4].token);

            JAXObjects.Token parm6 = new("");
            if (parms > 5)
                parm6.CopyFrom(Program.CurrentApp.ParameterClassList[5].token);


            // Can't connect when you already have a connection
            if (methodName.Equals(methConnect, StringComparison.OrdinalIgnoreCase))
            {
                if (await MyConnection.IsConnected())
                    result = 1541;
            }

            if (result == 0)
            {
                CurrentCursorName = cname;

                switch (EnglishMethodName)
                {
                    case "altertable":
                        if (parms > 0 && parm1.Element.Type.Equals("C") == false)
                            result = 11;

                        if (result == 0)
                        {
                            switch (parm1.AsString().ToUpper())
                            {
                                case "F":
                                    result = await MyConnection.AlterField(parm2.AsString(), parm3.AsString(), parm4.AsString(), parm5.AsInt(), parm6.AsInt());
                                    break;

                                case "P":
                                    result = await MyConnection.AlterProperty(parm2.AsString(), parm3.AsString(), parm4.AsString(), parm5);
                                    break;

                                case "I":
                                    result = await MyConnection.AlterIndex(parm2.AsString(), parm3.AsString(), parm4.AsString(), parm5.AsString());
                                    break;

                                case "D":
                                    result = await MyConnection.DropField(parm2.AsString(), parm3.AsString());
                                    break;

                                case "R":
                                    result = await MyConnection.DropIndex(parm2.AsString(), parm3.AsString());
                                    break;

                                default:
                                    result = 41;
                                    errMsg = parm1.AsString().ToUpper();
                                    break;
                            }

                            if (result > 0)
                                _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                        }
                        break;

                    case "connect":
                        if (parms > 1)
                        {
                            result = 96;
                            errMsg = "1";
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                        }
                        else
                        {
                            if (parms == 1)
                            {
                                if (parm1.Element.Type.Equals("C") == false)
                                    result = 11;
                            }
                            else
                                parm1.Element.Value = "";
                        }

                        if (result == 0)
                            result = await SQLConnect(parm1.AsString());
                        break;

                    case "createdatabase":
                        if (parms == 1)
                        {
                            if (parm1.Element.Type.Equals("C"))
                            {
                                if (AppHelper.IsLegalObjectName(parm1.AsString()))
                                    result = await MyConnection.CreateDatabase(parm1.AsString());
                                else
                                {
                                    result = 1575;
                                    errMsg = parm1.AsString();
                                    _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                }
                            }
                            else
                            {
                                result = 11;
                                _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                            }
                        }
                        else
                        {
                            result = 96;
                            errMsg = "1";
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                        }
                        break;

                    case "createtable":
                        if (parms == 2)
                        {
                            if (parm1.Element.Type.Equals("C"))
                            {
                                if (AppHelper.IsLegalObjectName(parm1.AsString()))
                                {
                                    if (parm2.TType.Equals("A"))
                                        result = await SQLCreateTable(parm1.AsString(), parm2);
                                    else
                                    {
                                        result = 232;
                                        errMsg = "Second parameter";
                                        _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                    }
                                }
                                else
                                {
                                    result = 1575;
                                    errMsg = parm1.AsString();
                                    _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                }
                            }
                            else
                            {
                                result = 11;
                                _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                            }
                        }
                        else
                        {
                            result = 96;
                            errMsg = "2";
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                        }
                        break;

                    case "sqlcreateindex":
                        break;

                    case "sqlcreateprocedure":
                        break;

                    case "createview":
                        if (parms == 2)
                        {
                            if (parm1.Element.Type.Equals("C") && parm2.Element.Type.Equals("C"))
                            {
                                if (AppHelper.IsLegalObjectName(parm1.AsString()))
                                    result = await SQLCreateView(parm1.AsString(), parm2.AsString());
                                else
                                {
                                    result = 1575;
                                    errMsg = parm1.AsString();
                                    _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                }
                            }
                            else
                                result = 11;
                        }
                        else
                        {
                            result = 96;
                            errMsg = "2";
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                        }
                        break;

                    case "disconnect":
                        result = await MyConnection.Disconnect();
                        break;

                    case "drop":
                        if (parm1.Element.Type.Equals("C") == false || parm2.Element.Type.Equals("C") == false)
                        {
                            result = 11;
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                        }
                        else
                        {
                            switch (parm1.AsString())
                            {
                                case "D":
                                    result = await MyConnection.DeleteDB(parm2.AsString());
                                    break;

                                case "I":
                                    if (parm3.Element.Type.Equals("C"))
                                        result = await MyConnection.DeleteIndex(parm2.AsString(), parm3.AsString());
                                    else
                                    {
                                        result = 11;
                                        _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                    }
                                    break;

                                case "P":
                                    result = await MyConnection.DeleteSP(parm2.AsString());
                                    break;

                                case "T":
                                    result = await MyConnection.DeleteTable(parm2.AsString());
                                    break;

                                case "V":
                                    result = await MyConnection.DeleteView(parm2.AsString());
                                    break;

                                default:
                                    result = 41;    // Unknown object type
                                    _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                    break;
                            }
                        }

                        break;

                    case "exec":
                        result = await SQLExec();
                        break;

                    case "getobjects":
                        if (parms >= 2)
                        {
                            if (parm1.Element.Type.Equals("C") && parm2.Element.Type.Equals("C"))
                            {
                                // Is there a parameter 3 and is it a character var?
                                if (parms > 2)
                                {
                                    if (parm3.Element.Type.Equals("C") == false)
                                    {
                                        result = 11;
                                        _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                    }
                                }
                                else
                                    parm3.Element.Value = "";   // No 3rd parameter so blank it out

                                string Name = parm2.AsString().Trim();
                                string cursorName = parm3.AsString().Trim();

                                if (result == 0)
                                {
                                    switch (parm1.AsString())
                                    {
                                        case "D":
                                            result = await MyConnection.GetDatabaseInfo(Name == "*" ? "" : Name, cursorName);
                                            break;

                                        case "I":
                                            result = await MyConnection.GetIndex(Name == "*" ? "" : Name, "", cursorName);
                                            break;

                                        case "P":
                                            result = await MyConnection.GetSPCode(Name == "*" ? "" : Name, cursorName);
                                            break;

                                        case "T":
                                            result = await MyConnection.GetTableStructure(Name == "*" ? "" : Name, cursorName);
                                            break;

                                        case "V":
                                            result = await MyConnection.GetView(Name == "*" ? "" : Name, cursorName);
                                            break;

                                        default:
                                            result = 41;    // Unknown object type
                                            _AddError(result, 0, parm1.AsString(), Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                            break;
                                    }
                                }
                            }
                            else
                            {
                                result = 11;
                                _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                            }
                        }

                        break;

                    default:
                        // Try base code
                        await base.DoDefault(methodName);
                        break;
                }

                if (Program.CurrentApp.CurrentDS.IsWorkArea(CurrentCursorName))
                    UserProperties[propCursorResult].Element.Value = CurrentCursorName;
            }

            return result > 0 ? -1 : result;
        }

        // --------------------------------------------------------------
        // COMMAND-KIND DETECTION
        // --------------------------------------------------------------
        public enum CommandKind { Select, Scalar, NonQuery }

        private static readonly Regex _selectRegex = new Regex(
            @"^\s*(SELECT)\s", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private static readonly Regex _scalarRegex = new Regex(
            @"^\s*(SELECT)\s+COUNT\s*\(|TOP\s*1\s|TOP\s*\(\s*\d+\s*\)",
            RegexOptions.IgnoreCase | RegexOptions.Compiled);

        public static CommandKind DetectCommandKind(string sql)
        {
            // Trim comments
            sql = Regex.Replace(sql, @"--.*?$|/\*.*?\*/", string.Empty,
                                 RegexOptions.Multiline | RegexOptions.IgnoreCase);

            var match = _selectRegex.Match(sql);
            if (!match.Success) return CommandKind.NonQuery;

            // If it starts with SELECT but looks like a scalar (COUNT(*) or TOP 1)
            if (_scalarRegex.IsMatch(sql))
                return CommandKind.Scalar;

            return CommandKind.Select;
        }

        /* -- Basic tools -----------------------------------------------
         * 
         * Connect to the SQL Engine
         * 
         * -------------------------------------------------------------- */
        private async Task<int> SQLConnect(string connString)
        {
            int result = 0;
            string errMsg = string.Empty;

            if (MyConnection is null || await MyConnection.IsConnected() == false)
            {
                try
                {
                    // Select the SQL Engine class and set it up
                    switch (UserProperties[propEngine].AsInt())
                    {
                        case 0: // Not chosen
                            result = 6005;
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                            break;

                        case 1: // SQL Server
                            me.nvObject = new XBase_ClassSQL_MSSS(this);
                            break;

                        case 2: // MySQL
                            me.nvObject = new XBase_ClassSQL_MYSQL(this);
                            break;

                        case 3: // PostGreSQL
                            me.nvObject = new XBase_ClassSQL_POSTGRE(this);
                            break;

                        default:    // Not chosen
                            result = 1999;
                            errMsg = $"Not implemented: Engine={UserProperties[propEngine].AsInt()}";
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                            break;

                    }
                }
                catch (Exception ex)
                {
                    result = 9999;
                    errMsg = ex.Message;
                    _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                }

                if (result == 0)
                {
                    if (string.IsNullOrWhiteSpace(connString) == false)
                        UserProperties[propConnectString].Element.Value = connString;

                    if (string.IsNullOrWhiteSpace(connString) && UserProperties[propConnectString].Element.Type.Equals("C"))
                        connString = UserProperties[propConnectString].AsString();
                    else
                        connString = "";

                    result = await MyConnection!.Connect(connString);

                }
            }
            else
            {
                result = 1541;
                _AddError(result, 0, string.Empty, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
            }

            return result;
        }



        // --------------------------------------------------------------
        // Execute a SQL command
        // --------------------------------------------------------------
        private async Task<int> SQLExec()
        {
            int result = 0;
            string errMsg = string.Empty;

            // Returns -1 if error otherwise returns
            // number of rows returned or affected by
            // the sql statement.
            if (MyConnection is null || await MyConnection.IsConnected() == false)
            {
                result = 6004;
                _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
            }
            else
            {
                string sqlStmt = string.Empty;
                string sqlCursor = string.Empty;

                if (Program.CurrentApp.ParameterClassList.Count == 0)
                {
                    // ERROR!
                    result = 1498;
                    _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                }
                else
                {
                    if (Program.CurrentApp.ParameterClassList[0].token.Element.Type.Equals("C"))
                    {
                        sqlStmt = Program.CurrentApp.ParameterClassList[0].token.AsString();
                    }
                    else
                    {
                        // ERROR!
                        result = 11;
                        _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                    }

                    if (Program.CurrentApp.ParameterClassList.Count == 2)
                    {
                        if (Program.CurrentApp.ParameterClassList[1].token.Element.Type.Equals("C"))
                            sqlCursor = Program.CurrentApp.ParameterClassList[1].token.AsString();
                        else
                        {
                            result = 11;
                            _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                        }
                    }
                    else if (Program.CurrentApp.ParameterClassList.Count > 2)
                    {
                        result = 1230;
                        _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                    }
                    else
                        sqlCursor = me.cPropSQLResult;
                }


                if (result > 0)
                {
                    Program.CurrentApp.ReturnValue.Element.Value = -1;
                }
                else
                {
                    // Execute the SQL Statement
                    result = await MyConnection.Execute(sqlStmt, sqlCursor);

                    if (result < 0)
                    {
                        // Cursors, tables, and views are all "dbfs"
                        await Program.CurrentApp.CurrentDS.CloseDBF(sqlCursor);
                        Program.CurrentApp.ReturnValue.Element.Value = -1;
                    }
                }
            }

            return result > 0 ? -1 : 0;
        }


        /* -----------------------------------------------------------------------------------------
         *  Create a table named by parameter 1 and described in the array reference by parameter 2
         *  
         *  The standard JAXBase array references, which is compatible with the VFP 9 standard will
         *  be converted by the SQL engine and a table will be created.  All tables created via 
         *  this method will only use field types that are compatible with JAXBase.
         *  
         *  The max field name length and other limitations are enforced by the engine.  This 
         *  method just collects the information and passes it on.
         *  
         *  The array in the second parameter can be passed as an array, or as a string referencing
         *  the array name. If the array has 4 or more columns but less than 18, the first four
         *  columns (name, type, length, and precision) are used.
         *  
         *  If the array has at least 18 columns, all JAXBase supported columns are used.
         *  
         *  If any array element used has an invalid type, the whole process ends with an error 11.
         * ----------------------------------------------------------------------------------------- */
        private async Task<int> SQLCreateTable(string tableName, JAXObjects.Token tk)
        {
            int result = 0;
            string errMsg = "";
            List<JAXTables.FieldInfo> fieldList = [];

            if (MyConnection is null || await MyConnection.IsConnected() == false)
                result = 6004;
            else
            {
                // Make sure the token is an array reference
                if (tk.TType.Equals("A") == false)
                {
                    result = 232;
                    errMsg = "Second parameter";
                    _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                }

                if (result == 0)
                {
                    // Two dimensional tables have Row>=1 while 1 dimensional have Row=0
                    // So make sure Row>0 and Col>3
                    if (tk.Row > 0 && tk.Col > 3)
                    {
                        bool typeError = false;

                        for (int i = 0; i < tk.Row; i++)
                        {

                            JAXTables.FieldInfo fld = new();

                            // Field Name
                            tk.SetElement(i + 1, 1);
                            typeError = tk.Element.Type.Equals("C");
                            fld.FieldName = tk.AsString();

                            // Field Type
                            tk.SetElement(i + 1, 2);
                            typeError = typeError & tk.Element.Type.Equals("C");
                            fld.FieldType = tk.AsString();

                            // Field Length
                            tk.SetElement(i + 1, 3);
                            typeError = typeError & tk.Element.Type.Equals("N");
                            fld.FieldLen = tk.AsInt();

                            // Field Precision
                            tk.SetElement(i + 1, 4);
                            typeError = typeError & tk.Element.Type.Equals("N");
                            fld.FieldDec = tk.AsInt();

                            // At least 18 columns are required to add extended properties
                            if (tk.Col > 17)
                            {
                                // Nulls allowed if true
                                tk.SetElement(i + 1, 5);
                                typeError = typeError & tk.Element.Type.Equals("L");
                                fld.NullOK = tk.AsBool();

                                // CP Translation not allowed if true
                                tk.SetElement(i + 1, 6);
                                typeError = typeError & tk.Element.Type.Equals("L");
                                fld.NoCPTrans = tk.AsBool();

                                // Default Value string
                                tk.SetElement(i + 1, 9);
                                typeError = typeError & tk.Element.Type.Equals("C");
                                fld.DefaultValue = tk.AsString();

                                // Table Name
                                tk.SetElement(i + 1, 12);
                                typeError = typeError & tk.Element.Type.Equals("C");
                                fld.TableName = tk.AsString();

                                // Comment
                                tk.SetElement(i + 1, 16);
                                typeError = typeError & tk.Element.Type.Equals("C");
                                fld.Comment = tk.AsString();

                                // AutoInc Next Value
                                tk.SetElement(i + 1, 17);
                                typeError = typeError & tk.Element.Type.Equals("N");
                                fld.AutoIncNext = tk.AsInt();

                                // AutoInc Step
                                tk.SetElement(i + 1, 18);
                                typeError = typeError & tk.Element.Type.Equals("N");
                                fld.AutoIncStep = tk.AsInt();
                                fld.AutoIncrement = fld.AutoIncStep > 0;
                            }

                            // If a type error was encountered, then set the
                            // error and drop out of the loop
                            if (typeError)
                            {
                                result = 11;
                                _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                                break;
                            }
                        }
                    }
                    else
                    {
                        result = 7002;
                        errMsg = "4";
                        _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
                    }
                }

                if (result == 0)
                    result = await MyConnection.CreateTable(tableName, fieldList);
            }

            return result > 0 ? -1 : 0;
        }


        // --------------------------------------------------------------
        // Create a view in the database
        // --------------------------------------------------------------
        private async Task<int> SQLCreateView(string viewName, string procCode)
        {
            int result = 0;
            string errMsg = "";

            if (MyConnection is null || await MyConnection.IsConnected() == false)
            {
                result = 6004;
                _AddError(result, 0, errMsg, Program.CurrentApp.AppLevels[Program.CurrentApp.CurrentAppLevel].Procedure);
            }
            else
            {
            }

            return result;
        }



        public override string[] JAXMethods() =>
            [
            "addproperty", "connect", "create", "drop", "disconnect", "exec", "getobjects",
            "truncate", "update", "writeexpression", "writemethod"
            ];

        public override string[] JAXEvents() =>
            [
            "afterquery", "connected", "disconnected", "destroy", "error", "fail", "init", "load", "success"
            ];

        /*
         * property data types
         *      C = Character
         *      N = Numeric         I=Integer       R=Color
         *      D = Date
         *      T = DateTime
         *      L = Logical         LY = Yes/No logical
         *      
         *      Attributes
         *          ! Protected - can't change after initialization
         *          $ Special Handling - do not auto process
         */
        public override string[] JAXProperties() =>
                [
                $"appname,C,{Program.CurrentApp.AppLevels[1].PrgName}", "asynchronous,L,F", "authtype,n,1",
                "baseclass,C!,SQL","batchmode,L,true",
                "class,C!,SQL", "classlibrary,C$,", "comment,C,", "connectionstring,c,", "connecttimeout,n,30", "cursorname,c,SQLResult", "cursorresult,c!,",
                "database,c,", "disconnectrollback,l,F", "displogin,n,1", "dispwarnings,L,F", "driver,c,",
                "encryption,L,F", "engine,N,0",
                "idletimeout,n,0", "isconnected,L!,F",
                "manual,n,1",
                "name,C,SQL",
                "packetsize,n,4096","parent,o$,","parentclass,C$,", "password,c,", "port,n,0",
                "querytimeout,n,30",
                "server,c,", "schema,c,dbo", "shared,l,f", "state,n!,0", "status,n!,0",
                "tag,C,", "thumbprint,c,", "transactions,n,1", "trust,L,T",
                "userid,c,",
                "waittime,n,100"
                ];
    }
}
